### PR TITLE
"Component" and "Module" in one package HOTFIX

### PR DESCRIPTION
**Pull request by michalbundyra**
If we have package which have `component` and `module` defined in `extra.zf` then both are prepended or appended on the module list. Please have a look on these tests.

Please notice that only ONE difference in these two tests is:

``` php
        $package->getExtra()->willReturn(['zf' => [
            'module' => 'Some\\Module',
            'component' => 'Some\\Component',
        ]]);
```

and:

``` php
        $package->getExtra()->willReturn(['zf' => [
            'component' => 'Some\\Component',
            'module' => 'Some\\Module',
        ]]);
```

It shouldn't matter what order of modules/components we have in `extra.zf` and the result should be always the same: modules should be appended and components prepended, so:

```
        'Some\Component',
        'SomeApplication',
        'Some\Module',
```

As we can see test `testAppendModuleAndPrependComponent` now failing because current result is:

```
        'SomeApplication'
        'Some\Component'
        'Some\Module'
```

(both appended).

and test `testPrependComponentAndAppendModule` is failing because current result is:

```
        'Some\Module'
        'Some\Component'
        'SomeApplication'
```

(both prepended).

### CODE REVIEW

**Comment by weierophinney** [comment]
Why are you defining both a component **and** a module in the same package? This was never an intended use case...

**Comment by michalbundyra** [comment]
> This was never an intended use case...

@weierophinney where it is said?
I think documentation clearly said: "one or more of the following keys"
https://github.com/zendframework/zend-component-installer#writing-packages-that-utilize-the-installer
and example there is also with `module` and `component`.

If so, maybe we should have some check in the library to catch situation when package with module and component try to be installed?

Maybe it is wrong if somebody has a package with two parts where one should be added as a module and the other one as a component, but it's possible.

**Comment by michalbundyra** [comment]
@weierophinney Please have a look on my changes in 78ada61.

**Comment by weierophinney** [comment]
Thanks, @webimpress

**Pull request merged**
