### PR TITLE
Auto include Module classes only for components not for modules

### PR DESCRIPTION
**Pull request by michalbundyra**
As noticed by @jguittard in https://github.com/zfcampus/zf-apigility-doctrine/pull/267#issuecomment-253712661 Module classes which implements some interfaces can't be autoloaded. Component installer needs to include only Module classes for component (because dependencies are checked only for component - when package have to be added on top).
This fix (hack...) include only Module classes when package type is component.
It is temporary solution, still it is not gonna work when component implements some interface. So far I don't know any package which is exposed as component and Module class implements some interfaces.

/cc @weierophinney @jguittard

### CODE REVIEW

**Comment by jguittard** [comment]
@weierophinney any chance a quick 0.4.1 release?

**Comment by michalbundyra** [comment]
As long as it is not yet merged maybe we can go further and eliminate `include` at all. My idea is to use regular expression to extract method `getModuleDependencies`.

Do you think is it gonna be better solution?

/cc @weierophinney @jguittard

**Comment by weierophinney** [comment]
I'd argue either regex or tokenization; the latter is more reliable, but
would involve more code. Either way, stability and reliability should be
the goal.

Thanks, @webimpress!

**Comment by weierophinney** [comment]
Closing, in favor of #24.

**Pull request closed without merging**
